name: tdlib
description: Dart port of the Telegram Database Library (TDLib)
version: 0.3.1
author:  Aidan T. Manning <periodicaidan@gmail.com>

# Since dart:ffi isn't a stable feature yet you have to be on the latest dev channel
environment:
  sdk: '>=2.6.0-dev.8.2 <3.0.0'

dependencies:
  path: ^1.6.4
  meta: ^1.1.8
  reflectable: ^2.2.0
  rxdart: ^0.24.0

dev_dependencies:
  pedantic: '^1.7.0'
  test: '^1.6.0'
  build_runner: ^1.0.0
